---
version: '3.8'
secrets:
  app_secrets:
    file: ./secrets/app_secrets
services:
  app:
    image: ghcr.io/ramblurr/probematic:latest
    restart: always
    environment:
      APP_SECRETS_FILE: /run/secrets/app_secrets
      DATOMIC_DB_STORAGE_DIR: /data/datomic
      HTTP_BIND_HOST: 0.0.0.0
      HTTP_PORT: 6160
      APP_ENVIRONMENT: prod
    volumes:
      - "/srv/probematic/app:/data:z"
    secrets:
      - app_secrets
...
