(ns app.util.zip
  "Helpers for streaming ZIP files in HTTP responses.

  The application uses these functions when it needs to bundle generated or
  filestore-backed content without first materializing a complete archive on disk."
  (:require
   [clojure.java [io :as io]]
   [clojure.string :as s])
  (:import
   [java.io
    InputStream
    PipedInputStream
    PipedOutputStream]
   [java.nio.charset StandardCharsets]
   [java.text Normalizer Normalizer$Form]
   [java.util.zip ZipEntry ZipOutputStream]))

(defn de-accent
  "Returns `text` with Unicode accent marks removed.

  Returns `nil` when `text` is nil."
  [^String text]
  (when text
    (let [normalized (Normalizer/normalize text Normalizer$Form/NFD)]
      (s/replace normalized #"\p{InCombiningDiacriticalMarks}+" ""))))

(defn encode-filename
  "Returns a ZIP-entry-safe filename derived from `unencoded-filename`.

  The result keeps ASCII letters, numbers, dots, hyphens, underscores, and spaces.
  Accent marks are removed and all other characters are replaced with `-`.
  This avoids UTF-8 filename compatibility problems in ZIP tools."
  ^String [unencoded-filename]
  (when-let [de-accented (de-accent unencoded-filename)]
    (s/replace
     de-accented
     #"[^a-zA-Z0-9\.\-_ ]" "-")))

;; NOTE: I hate to have to use encode-filename here
;; in theory it should be possible to use utf-8 strings (like  wëird:user:înput:.jpeg)
;;  as zip entry file names, but the resulting zip files cannot be decompressed on linux:
;;  error:  cannot create instrument_w+?irduser+?nput.jpeg
;;          Invalid or incomplete multibyte or wide character
;;

(defn append-stream!
  "Appends input stream `in` to `zip` as a file named `file-name`.

  The entry name is normalized with [[encode-filename]].
  This function closes the ZIP entry, but it does not close `in` or `zip`.
  Returns `zip`.
  When `in` is nil, this is a no-op."
  [^ZipOutputStream zip file-name in]
  (when in
    (.putNextEntry zip (ZipEntry. (encode-filename file-name)))
    (io/copy in zip)
    (.closeEntry zip))
  zip)

(defn open-and-append!
  "Opens `(content-thunk)` and appends its bytes to `zip` as `file-name`.

  `content-thunk` must return an `InputStream`.
  The input stream is closed after copying.
  The ZIP stream is flushed so data can flow through streaming responses.
  Returns `zip`."
  [^ZipOutputStream zip file-name content-thunk]
  (with-open [in ^InputStream (content-thunk)]
    (append-stream! zip file-name in))
  ;; Flush after each attachment to ensure data flows into the output pipe
  (.flush zip)
  zip)

(defn piped-zip-input-stream
  "Returns an input stream for a ZIP archive generated by `content-fn`.

  `content-fn` receives a `ZipOutputStream` and runs in a future while callers read
  from the returned `InputStream`.
  The caller owns and must close the returned stream."
  ^InputStream [content-fn]
  (let [pos (PipedOutputStream.)
        ;; Use 16 MB pipe buffer
        is (PipedInputStream. pos 16777216)
        zip (ZipOutputStream. pos StandardCharsets/UTF_8)]
    (future
      ;; This runs in a separate thread so that the input stream can be returned immediately
      (try
        (content-fn zip)
        (.finish zip)
        (.flush zip)
        (catch Throwable t
          (throw (ex-info "Error occurred while generating ZIP output stream" {:msg (.getMessage t)} t)))
        (finally
          (.close zip)
          (.close pos))))
    is))

#_(defn- append-attachments-to-zip! [zip  attachments file-name-prefix]
    (doseq [{:keys [content file-name]} attachments]
      (when (and content file-name)
        (open-and-append! zip (str file-name-prefix "_" file-name) content))))

(comment

  (let [attachments [{:content (fn [] (io/input-stream "/home/ramblurr/downloads/Bela1(1).JPG"))
                      :file-name "Bela1(1).JPG"}
                     {:content (fn [] (io/input-stream "/home/ramblurr/downloads/Bela2(2).JPG"))
                      :file-name "Bela2(2).JPG"}]]
    (io/copy
     (piped-zip-input-stream
      (fn [zip]
        (append-attachments-to-zip! zip  attachments  "instrument")))
     (io/output-stream "/home/ramblurr/downloads/test-zip-r/test-zip.zip")))

  #_(let [out-f "/home/ramblurr/downloads/test-zip-r/test-zip.zip"
          zip (ZipOutputStream. (io/output-stream out-f))]
      (pack-folder! zip "/home/ramblurr/downloads/test-zip")
      (.finish zip)
      (.flush zip)
      (.close zip)
      out-f)

  ;;
  )
